# Financial Operations Analytics
## Notebook 1: Data Understanding
### Objective
Understand the structure, quality, and relationships of all datasets before cleaning and analysis.

In [1]:
import pandas as pd
import numpy as np

# Display settings
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.float_format", "{:.2f}".format)

In [2]:
accounts = pd.read_csv(r'C:\PROJECTS\Financial Operations analytics\Data\Raw\ravenstack_accounts.csv')
subscriptions = pd.read_csv('C:\\PROJECTS\\Financial Operations analytics\\Data\\Raw\\ravenstack_subscriptions.csv')
churn = pd.read_csv('C:\\PROJECTS\\Financial Operations analytics\\Data\\Raw\\ravenstack_churn_events.csv')
feature_usage = pd.read_csv('C:\\PROJECTS\\Financial Operations analytics\\Data\\Raw\\ravenstack_feature_usage.csv')
support = pd.read_csv('C:\\PROJECTS\\Financial Operations analytics\\Data\\Raw\\ravenstack_support_tickets.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\PROJECTS\\Financial Operations analytics\\Data\\Raw\\ravenstack_accounts.csv'

## Accounts Dataset

In [ ]:
accounts.head()

,account_id,account_name,industry,country,signup_date,referral_source,plan_tier,seats,is_trial,churn_flag
0,A-2e4581,Company_0,EdTech,US,2024-10-16,partner,Basic,9,False,False
1,A-43a9e3,Company_1,FinTech,IN,2023-08-17,other,Basic,18,False,True
2,A-0a282f,Company_2,DevTools,US,2024-08-27,organic,Basic,1,False,False
3,A-1f0ac7,Company_3,HealthTech,UK,2023-08-27,other,Basic,24,True,False
4,A-ce550d,Company_4,HealthTech,US,2024-10-27,event,Enterprise,35,False,True

In [ ]:
accounts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   account_id       500 non-null    object
 1   account_name     500 non-null    object
 2   industry         500 non-null    object
 3   country          500 non-null    object
 4   signup_date      500 non-null    object
 5   referral_source  500 non-null    object
 6   plan_tier        500 non-null    object
 7   seats            500 non-null    int64
 8   is_trial         500 non-null    bool
 9   churn_flag       500 non-null    bool
dtypes: bool(2), int64(1), object(7)
memory usage: 32.4+ KB

In [ ]:
accounts.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
account_id,500,500,A-2e4581,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
account_name,500,500,Company_0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
industry,500,5,DevTools,113,NaN,NaN,NaN,NaN,NaN,NaN,NaN
country,500,7,US,291,NaN,NaN,NaN,NaN,NaN,NaN,NaN
signup_date,500,370,2024-10-27,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
referral_source,500,5,organic,114,NaN,NaN,NaN,NaN,NaN,NaN,NaN
plan_tier,500,3,Pro,178,NaN,NaN,NaN,NaN,NaN,NaN,NaN
seats,500.00,NaN,NaN,NaN,20.56,21.04,1.00,5.00,15.00,28.00,163.00
is_trial,500,2,False,403,NaN,NaN,NaN,NaN,NaN,NaN,NaN
churn_flag,500,2,False,390,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
accounts.isnull().sum()

account_id         0
account_name       0
industry           0
country            0
signup_date        0
referral_source    0
plan_tier          0
seats              0
is_trial           0
churn_flag         0
dtype: int64

In [ ]:
accounts.duplicated().sum()

0

In [ ]:
accounts.nunique()

account_id         500
account_name       500
industry             5
country              7
signup_date        370
referral_source      5
plan_tier            3
seats               73
is_trial             2
churn_flag           2
dtype: int64

In [ ]:
accounts["industry"].value_counts()

industry
DevTools         113
FinTech          112
Cybersecurity    100
HealthTech        96
EdTech            79
Name: count, dtype: int64

In [ ]:
accounts["country"].value_counts()

country
US    291
UK     58
IN     49
AU     32
DE     25
CA     23
FR     22
Name: count, dtype: int64

In [ ]:
accounts["referral_source"].value_counts()

referral_source
organic    114
other      103
ads         98
event       96
partner     89
Name: count, dtype: int64

In [ ]:
accounts["plan_tier"].value_counts()

plan_tier
Pro           178
Basic         168
Enterprise    154
Name: count, dtype: int64

### Intial_Findings

- The dataset contains 5 industries.
- The company operates across 7 countries.
- There are 3 subscription plan tiers.
- Customers arrive through multiple referral sources.

## Subscriptions dataset

In [ ]:
subscriptions.head()

,subscription_id,account_id,start_date,end_date,plan_tier,seats,mrr_amount,arr_amount,is_trial,upgrade_flag,downgrade_flag,churn_flag,billing_frequency,auto_renew_flag
0,S-8cec59,A-3c1a3f,2023-12-23,2024-04-12,Enterprise,14,2786,33432,False,False,False,True,monthly,True
1,S-0f6f44,A-9b9fe9,2024-06-11,NaN,Pro,17,833,9996,False,False,False,False,monthly,True
2,S-51c0d1,A-659280,2024-11-25,NaN,Enterprise,62,0,0,True,True,False,False,annual,False
3,S-f81687,A-e7a1e2,2024-11-23,2024-12-13,Enterprise,5,995,11940,False,False,False,True,monthly,True
4,S-cff5a2,A-ba6516,2024-01-10,NaN,Enterprise,27,5373,64476,False,False,False,False,monthly,True

In [ ]:
subscriptions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   subscription_id    5000 non-null   object
 1   account_id         5000 non-null   object
 2   start_date         5000 non-null   object
 3   end_date           486 non-null    object
 4   plan_tier          5000 non-null   object
 5   seats              5000 non-null   int64
 6   mrr_amount         5000 non-null   int64
 7   arr_amount         5000 non-null   int64
 8   is_trial           5000 non-null   bool
 9   upgrade_flag       5000 non-null   bool
 10  downgrade_flag     5000 non-null   bool
 11  churn_flag         5000 non-null   bool
 12  billing_frequency  5000 non-null   object
 13  auto_renew_flag    5000 non-null   bool
dtypes: bool(5), int64(3), object(6)
memory usage: 376.1+ KB

In [ ]:
subscriptions.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
subscription_id,5000,5000,S-8cec59,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
account_id,5000,500,A-d4ac0e,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN
start_date,5000,625,2024-12-31,45,NaN,NaN,NaN,NaN,NaN,NaN,NaN
end_date,486,208,2024-12-31,24,NaN,NaN,NaN,NaN,NaN,NaN,NaN
plan_tier,5000,3,Enterprise,1723,NaN,NaN,NaN,NaN,NaN,NaN,NaN
seats,5000.00,NaN,NaN,NaN,29.85,23.09,1.00,14.00,24.00,40.00,189.00
mrr_amount,5000.00,NaN,NaN,NaN,2267.75,3421.38,0.00,285.00,931.00,2786.00,33830.00
arr_amount,5000.00,NaN,NaN,NaN,27212.99,41056.50,0.00,3420.00,11172.00,33432.00,405960.00
is_trial,5000,2,False,4222,NaN,NaN,NaN,NaN,NaN,NaN,NaN
upgrade_flag,5000,2,False,4471,NaN,NaN,NaN,NaN,NaN,NaN,NaN
downgrade_flag,5000,2,False,4782,NaN,NaN,NaN,NaN,NaN,NaN,NaN
churn_flag,5000,2,False,4514,NaN,NaN,NaN,NaN,NaN,NaN,NaN
billing_frequency,5000,2,monthly,2539,NaN,NaN,NaN,NaN,NaN,NaN,NaN
auto_renew_flag,5000,2,True,4005,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
subscriptions.isnull().sum()

subscription_id         0
account_id              0
start_date              0
end_date             4514
plan_tier               0
seats                   0
mrr_amount              0
arr_amount              0
is_trial                0
upgrade_flag            0
downgrade_flag          0
churn_flag              0
billing_frequency       0
auto_renew_flag         0
dtype: int64

In [ ]:
subscriptions.duplicated().sum()

0

In [ ]:
subscriptions.nunique()

subscription_id      5000
account_id            500
start_date            625
end_date              208
plan_tier               3
seats                 123
mrr_amount            306
arr_amount            306
is_trial                2
upgrade_flag            2
downgrade_flag          2
churn_flag              2
billing_frequency       2
auto_renew_flag         2
dtype: int64

In [ ]:
subscriptions['plan_tier'].value_counts()

plan_tier
Enterprise    1723
Pro           1675
Basic         1602
Name: count, dtype: int64

In [ ]:
subscriptions['billing_frequency'].value_counts()

billing_frequency
monthly    2539
annual     2461
Name: count, dtype: int64

### Intial_Findings

• The dataset contains subscription-related information for customer accounts.

• No duplicate records were found. (Only if duplicated().sum() == 0)

• The table includes subscription details such as plan_tier, seats, billing_cycle, start_date, end_date .

• The end_date column contains a large number of missing values (4514 out of 5000 records), which may indicate active subscriptions. This will be verified during the data cleaning phase.

• The seats column has 123 unique values, suggesting a wide variation in subscription sizes.

## Churn Dataset

In [ ]:
churn.head()

,churn_event_id,account_id,churn_date,reason_code,refund_amount_usd,preceding_upgrade_flag,preceding_downgrade_flag,is_reactivation,feedback_text
0,C-816288,A-c37cab,2024-10-27,pricing,4.03,False,False,False,switched to competitor
1,C-5a81e7,A-37f969,2024-06-25,support,96.45,True,False,False,NaN
2,C-a174be,A-b07346,2024-11-12,budget,0.00,False,False,False,missing features
3,C-accb39,A-1e50e0,2023-11-01,budget,54.94,False,False,False,switched to competitor
4,C-92f889,A-956988,2024-12-30,unknown,0.00,False,True,True,too expensive

In [ ]:
churn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   churn_event_id            600 non-null    object
 1   account_id                600 non-null    object
 2   churn_date                600 non-null    object
 3   reason_code               600 non-null    object
 4   refund_amount_usd         600 non-null    float64
 5   preceding_upgrade_flag    600 non-null    bool
 6   preceding_downgrade_flag  600 non-null    bool
 7   is_reactivation           600 non-null    bool
 8   feedback_text             452 non-null    object
dtypes: bool(3), float64(1), object(5)
memory usage: 30.0+ KB

In [ ]:
churn.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
churn_event_id,600,600,C-816288,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
account_id,600,352,A-180abf,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
churn_date,600,311,2024-12-29,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
reason_code,600,6,features,114,NaN,NaN,NaN,NaN,NaN,NaN,NaN
refund_amount_usd,600.00,NaN,NaN,NaN,14.42,39.22,0.00,0.00,0.00,0.00,392.92
preceding_upgrade_flag,600,2,False,477,NaN,NaN,NaN,NaN,NaN,NaN,NaN
preceding_downgrade_flag,600,2,False,547,NaN,NaN,NaN,NaN,NaN,NaN,NaN
is_reactivation,600,2,False,539,NaN,NaN,NaN,NaN,NaN,NaN,NaN
feedback_text,452,3,too expensive,161,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
churn.isnull().sum()

churn_event_id                0
account_id                    0
churn_date                    0
reason_code                   0
refund_amount_usd             0
preceding_upgrade_flag        0
preceding_downgrade_flag      0
is_reactivation               0
feedback_text               148
dtype: int64

In [ ]:
churn.duplicated().sum()

0

In [ ]:
churn.nunique()

churn_event_id              600
account_id                  352
churn_date                  311
reason_code                   6
refund_amount_usd           142
preceding_upgrade_flag        2
preceding_downgrade_flag      2
is_reactivation               2
feedback_text                 3
dtype: int64

In [ ]:
churn['reason_code'].value_counts()

reason_code
features      114
support       104
budget        104
unknown        95
competitor     92
pricing        91
Name: count, dtype: int64

In [ ]:
churn['feedback_text'].value_counts()

feedback_text
too expensive             161
missing features          155
switched to competitor    136
Name: count, dtype: int64

### Intial_Findings

• The dataset contains 600 churn event records with 9 columns.

• Missing values are present in the feedback_text column.

• The reason_code column contains an "Unknown" category, which will be reviewed during the data cleaning phase to determine whether it represents missing information or a valid business category.

• No duplicate records were found. (Only if duplicated().sum() == 0)

## Feature_Usage Dataset

In [ ]:
feature_usage.head()

,usage_id,subscription_id,usage_date,feature_name,usage_count,usage_duration_secs,error_count,is_beta_feature
0,U-1c6c24,S-0fcf7d,2023-07-27,feature_20,9,5004,0,False
1,U-f07cb8,S-c25263,2023-08-07,feature_5,9,369,0,False
2,U-096807,S-f29e7f,2023-12-07,feature_3,9,1458,0,False
3,U-6b1580,S-be655e,2024-07-28,feature_40,5,2085,0,False
4,U-720a29,S-f9b1d0,2024-12-02,feature_12,12,900,0,False

In [ ]:
feature_usage.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   usage_id             25000 non-null  object
 1   subscription_id      25000 non-null  object
 2   usage_date           25000 non-null  object
 3   feature_name         25000 non-null  object
 4   usage_count          25000 non-null  int64
 5   usage_duration_secs  25000 non-null  int64
 6   error_count          25000 non-null  int64
 7   is_beta_feature      25000 non-null  bool
dtypes: bool(1), int64(3), object(4)
memory usage: 1.4+ MB

In [ ]:
feature_usage.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
usage_id,25000,24979,U-6970d1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
subscription_id,25000,4967,S-0896f4,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN
usage_date,25000,731,2024-10-11,53,NaN,NaN,NaN,NaN,NaN,NaN,NaN
feature_name,25000,40,feature_32,659,NaN,NaN,NaN,NaN,NaN,NaN,NaN
usage_count,25000.00,NaN,NaN,NaN,10.02,3.14,0.00,8.00,10.00,12.00,26.00
usage_duration_secs,25000.00,NaN,NaN,NaN,3042.20,2056.54,0.00,1350.00,2760.00,4400.00,12696.00
error_count,25000.00,NaN,NaN,NaN,0.56,1.01,0.00,0.00,0.00,1.00,8.00
is_beta_feature,25000,2,False,22456,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
feature_usage.isnull().sum()

usage_id               0
subscription_id        0
usage_date             0
feature_name           0
usage_count            0
usage_duration_secs    0
error_count            0
is_beta_feature        0
dtype: int64

In [ ]:
feature_usage.duplicated().sum()

0

In [ ]:
feature_usage.nunique()

usage_id               24979
subscription_id         4967
usage_date               731
feature_name              40
usage_count               27
usage_duration_secs     4168
error_count                9
is_beta_feature            2
dtype: int64

In [ ]:
feature_usage["feature_name"].value_counts()

feature_name
feature_32    659
feature_12    659
feature_6     655
feature_17    651
feature_34    650
feature_26    649
feature_36    648
feature_31    644
feature_20    643
feature_24    643
feature_11    643
feature_38    643
feature_2     642
feature_29    640
feature_15    640
feature_37    636
feature_22    636
feature_33    635
feature_10    634
feature_39    631
feature_1     629
feature_30    629
feature_4     625
feature_9     624
feature_28    623
feature_16    622
feature_40    621
feature_7     619
feature_25    615
feature_13    612
feature_27    611
feature_14    600
feature_3     598
feature_8     596
feature_21    591
feature_19    589
feature_18    588
feature_35    587
feature_5     577
feature_23    563
Name: count, dtype: int64

In [ ]:
feature_usage['error_count'].value_counts()

error_count
0    17269
1     3759
2     2312
3     1096
4      419
5      113
6       30
7        1
8        1
Name: count, dtype: int64

### Intial_Findings

• The dataset contains 25,000 feature usage records with 8 columns.

• No missing values are present in any of the columns.

• The feature_name column contains different product features that will be analyzed further during the exploratory data analysis (EDA) phase.

• The usage_id column appears to uniquely identify each feature usage record, while subscription_id links usage activity to customer subscriptions.

## Support Dataset

In [ ]:
support.head()

,ticket_id,account_id,submitted_at,closed_at,resolution_time_hours,priority,first_response_time_minutes,satisfaction_score,escalation_flag
0,T-0024de,A-712f1c,2023-07-27,2023-07-28 03:00:00,27.00,high,74,NaN,False
1,T-4d04b9,A-e43bf7,2024-07-08,2024-07-09 03:00:00,27.00,urgent,144,NaN,False
2,T-d5e12f,A-0f3e88,2024-10-17,2024-10-17 19:00:00,19.00,urgent,93,4.00,False
3,T-dfce9a,A-4c56c9,2024-09-08,2024-09-09 23:00:00,47.00,medium,126,5.00,False
4,T-c59f77,A-6f8ad2,2024-11-30,2024-12-01 02:00:00,26.00,medium,8,NaN,False

In [ ]:
support.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ticket_id                    2000 non-null   object
 1   account_id                   2000 non-null   object
 2   submitted_at                 2000 non-null   object
 3   closed_at                    2000 non-null   object
 4   resolution_time_hours        2000 non-null   float64
 5   priority                     2000 non-null   object
 6   first_response_time_minutes  2000 non-null   int64
 7   satisfaction_score           1175 non-null   float64
 8   escalation_flag              2000 non-null   bool
dtypes: bool(1), float64(2), int64(1), object(5)
memory usage: 127.1+ KB

In [ ]:
support.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
ticket_id,2000,2000,T-0024de,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
account_id,2000,492,A-bb3bd4,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN
submitted_at,2000,671,2024-12-01,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
closed_at,2000,1893,2024-04-28 03:00:00,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
resolution_time_hours,2000.00,NaN,NaN,NaN,35.86,21.14,1.00,17.00,35.00,54.00,72.00
priority,2000,4,urgent,514,NaN,NaN,NaN,NaN,NaN,NaN,NaN
first_response_time_minutes,2000.00,NaN,NaN,NaN,88.48,51.53,1.00,43.00,88.00,131.00,180.00
satisfaction_score,1175.00,NaN,NaN,NaN,3.98,0.81,3.00,3.00,4.00,5.00,5.00
escalation_flag,2000,2,False,1905,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
support.isnull().sum()

ticket_id                        0
account_id                       0
submitted_at                     0
closed_at                        0
resolution_time_hours            0
priority                         0
first_response_time_minutes      0
satisfaction_score             825
escalation_flag                  0
dtype: int64

In [ ]:
support.duplicated().sum()

0

In [ ]:
support.nunique()

ticket_id                      2000
account_id                      492
submitted_at                    671
closed_at                      1893
resolution_time_hours            72
priority                          4
first_response_time_minutes     180
satisfaction_score                3
escalation_flag                   2
dtype: int64

In [ ]:
support['priority'].value_counts()

priority
urgent    514
high      510
medium    491
low       485
Name: count, dtype: int64

In [ ]:
support['satisfaction_score'].value_counts()

satisfaction_score
4.00    405
3.00    396
5.00    374
Name: count, dtype: int64

### Intial_Findings

• The dataset contains 2,000 support ticket records with 9 columns.

• No duplicate records were found. (Assuming duplicated().sum() = 0)

• The satisfaction_score column contains 825 missing values. This will be investigated during the data cleaning phase to determine whether the missing values represent customers who did not submit feedback after ticket resolution.

• The priority column contains four categories, indicating different ticket priority levels.

• The account_id column contains 492 unique customer accounts, suggesting that some accounts have raised multiple support tickets.