In [1]:
import pandas as pd
import numpy as np 

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [2]:
accounts = pd.read_csv(r'C:\PROJECTS\Financial Operations analytics\Data\Raw\ravenstack_accounts.csv')
subscriptions = pd.read_csv('C:\\PROJECTS\\Financial Operations analytics\\Data\\Raw\\ravenstack_subscriptions.csv')
churn = pd.read_csv('C:\\PROJECTS\\Financial Operations analytics\\Data\\Raw\\ravenstack_churn_events.csv')
feature_usage = pd.read_csv('C:\\PROJECTS\\Financial Operations analytics\\Data\\Raw\\ravenstack_feature_usage.csv')
support = pd.read_csv('C:\\PROJECTS\\Financial Operations analytics\\Data\\Raw\\ravenstack_support_tickets.csv')

### Changing Data Types for Time-data

In [5]:
accounts["signup_date"] = pd.to_datetime(accounts["signup_date"])

subscriptions["start_date"] = pd.to_datetime(subscriptions["start_date"])
subscriptions["end_date"] = pd.to_datetime(subscriptions["end_date"])

feature_usage["usage_date"] = pd.to_datetime(feature_usage["usage_date"])

support["submitted_at"] = pd.to_datetime(support["submitted_at"])
support["closed_at"] = pd.to_datetime(support["closed_at"])

churn["churn_date"] = pd.to_datetime(churn["churn_date"])

###  Subscriptions Dataset

In [9]:
subscriptions["is_active"] = subscriptions["end_date"].isna()

In [10]:
subscriptions.head()

,subscription_id,account_id,start_date,end_date,plan_tier,seats,mrr_amount,arr_amount,is_trial,upgrade_flag,downgrade_flag,churn_flag,billing_frequency,auto_renew_flag,is_active
0,S-8cec59,A-3c1a3f,2023-12-23,2024-04-12,Enterprise,14,2786,33432,False,False,False,True,monthly,True,False
1,S-0f6f44,A-9b9fe9,2024-06-11,NaT,Pro,17,833,9996,False,False,False,False,monthly,True,True
2,S-51c0d1,A-659280,2024-11-25,NaT,Enterprise,62,0,0,True,True,False,False,annual,False,True
3,S-f81687,A-e7a1e2,2024-11-23,2024-12-13,Enterprise,5,995,11940,False,False,False,True,monthly,True,False
4,S-cff5a2,A-ba6516,2024-01-10,NaT,Enterprise,27,5373,64476,False,False,False,False,monthly,True,True

### Churn Dataset

In [14]:
churn[churn["feedback_text"].isna()]

,churn_event_id,account_id,churn_date,reason_code,refund_amount_usd,preceding_upgrade_flag,preceding_downgrade_flag,is_reactivation,feedback_text
1,C-5a81e7,A-37f969,2024-06-25,support,96.45,True,False,False,NaN
6,C-2e2966,A-526d93,2024-07-10,features,34.40,True,False,False,NaN
7,C-ee531b,A-751bd4,2024-09-22,budget,0.00,False,False,False,NaN
12,C-bb3556,A-bcf664,2024-08-08,competitor,0.00,False,False,False,NaN
23,C-e582ea,A-180abf,2023-12-04,support,0.00,False,False,False,NaN
...,...,...,...,...,...,...,...,...,...
583,C-a860c5,A-5f7781,2024-12-25,pricing,0.00,False,False,False,NaN
589,C-c4582f,A-9f0b68,2024-11-01,pricing,0.00,True,False,False,NaN
596,C-7e7822,A-dbc825,2024-02-03,budget,0.00,False,False,False,NaN
598,C-22f536,A-e5d6ab,2024-05-11,competitor,0.00,True,False,False,NaN
599,C-5e0b68,A-1f559b,2024-09-28,features,0.00,False,False,False,NaN

In [18]:
churn[churn['reason_code'] == 'unknown'].head(5)

,churn_event_id,account_id,churn_date,reason_code,refund_amount_usd,preceding_upgrade_flag,preceding_downgrade_flag,is_reactivation,feedback_text
4,C-92f889,A-956988,2024-12-30,unknown,0.00,False,True,True,too expensive
11,C-c54ef0,A-3b5cd1,2024-08-30,unknown,77.87,False,False,False,missing features
29,C-8b229b,A-44dc83,2024-11-29,unknown,98.48,False,True,False,missing features
30,C-7d13bf,A-78f02b,2024-12-02,unknown,0.00,False,False,False,missing features
32,C-935f48,A-34ea2f,2024-10-05,unknown,0.00,True,False,False,NaN

In [19]:
support[support["satisfaction_score"].isna()].head(5)

,ticket_id,account_id,submitted_at,closed_at,resolution_time_hours,priority,first_response_time_minutes,satisfaction_score,escalation_flag
0,T-0024de,A-712f1c,2023-07-27,2023-07-28 03:00:00,27.0,high,74,NaN,False
1,T-4d04b9,A-e43bf7,2024-07-08,2024-07-09 03:00:00,27.0,urgent,144,NaN,False
4,T-c59f77,A-6f8ad2,2024-11-30,2024-12-01 02:00:00,26.0,medium,8,NaN,False
5,T-90f06d,A-94c3cd,2023-07-27,2023-07-27 09:00:00,9.0,medium,60,NaN,False
8,T-7119c9,A-b179bf,2023-08-27,2023-08-27 16:00:00,16.0,urgent,154,NaN,False

In [21]:
accounts.to_csv("../Data/Processed/accounts_cleaned.csv", index=False)

subscriptions.to_csv("../Data/Processed/subscriptions_cleaned.csv", index=False)

feature_usage.to_csv("../Data/Processed/feature_usage_cleaned.csv", index=False)

support.to_csv("../Data/Processed/support_cleaned.csv", index=False)

churn.to_csv("../Data/Processed/churn_cleaned.csv", index=False)

# Cleaning Summary

## Cleaning Actions Performed
- Converted date columns to datetime format.

### Accounts
- No cleaning was required.
- No missing values or duplicate records were identified.

### Subscription
- Retained missing values in the `end_date` column as they likely represent active subscriptions.
- Created a new `is_active` column based on the availability of `end_date`.

### Feature Usage
- No cleaning was required.
- The dataset contained no missing values or duplicate records.

### Support Tickets

- Retained missing values in `satisfaction_score` since customer feedback is optional.

### Churn Events
- The `reason_code` value "unknown" was retained because it represents a valid business category rather than missing data.
- Missing values in `feedback_text` were retained since customer feedback is optional and the absence of feedback is meaningful.

---

## Output

The cleaned datasets have been exported to the `Data/Processed` directory and will be used for all subsequent analyses, including:

- Exploratory Data Analysis (EDA)
- SQL Business Analysis
- Power BI Dashboard Development
- Machine Learning Models